x-app:
  name: nextcloud
  title: Nextcloud
  description: >
    With over 400.000 deployments, Nextcloud is the most popular on-premises
    content collaboration platform you can download. 

    It scales from a Raspberry Pi with 2 users to globally distributed installations with tens of millions of users at major hosting providers.
  url: https://nextcloud.com/
  category: office
  icon: nextcloud.png
  author: Koen Swings
  version: 6900555403c84463e2c8ac53e49cc9c08536669e
  instanceName: nextcloud
networks:
  backend: null
services:
  nextcloud-app:
    #image: nextcloud
    image: koenswings/nextcloud:1.0-31.0.1
    restart: no
    pull_policy: never
    volumes:
      - ./data/nextcloud:/var/www/html
    ports:
      - ${port}:80
    environment:
      - MYSQL_PASSWORD=${pass}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
    networks:
      - backend
  nextcloud-db:
    #image: mariadb
    image: koenswings/nextcloud-mariadb:1.0-11.7.2-MariaDB-ubu2404
    restart: no
    pull_policy: never
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${pass}
      - MYSQL_PASSWORD=${pass}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
  code:
    #image: collabora/code
    image: koenswings/nextcloud-code:1.0-24.04.13.2
    restart: no
    pull_policy: never
    ports:
      - 9980:9980
    environment:
      - extra_params=--o:ssl.enable=false
    extra_hosts:
      - ${hostname}.local:${ip}
    networks:
      - backend
