x-app:
  name: nextcloud
  title: Nextcloud
  description: |
    With over 400.000 deployments, Nextcloud is the most popular on-premises content collaboration platform you can download. 
    It scales from a Raspberry Pi with 2 users to globally distributed installations with tens of millions of users at major hosting providers.
  url: https://nextcloud.com/
  category: office
  icon: nextcloud.png
  author: Koen Swings  # Who created this compose file? (not the app ;-)
networks:
  backend:
services:
  nextcloud-app:
    image: nextcloud
    restart: no
    pull_policy: never
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=admin911!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
  nextcloud-db:
    image: mariadb
    restart: no
    pull_policy: never
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - ./data/nextcloud:/var/lib/mysql
    ports:
      - ${port}:80
    environment:
      - MYSQL_ROOT_PASSWORD=admin911!
      - MYSQL_PASSWORD=admin911!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
  code:
    image: collabora/code
    restart: no
    pull_policy: never
    ports:
      - 9980:9980
    #security_opt:
    #  - seccomp:unconfined
    #cap_add:
    #  - MKNOD
    #  - SYS_CHROOT
    #  - FOWNER
    environment:
      - extra_params=--o:ssl.enable=false
    extra_hosts:
      - "nextcloud.boringeinstein.net:172.17.0.1"
    networks:
      - backend
