x-app:
  name: nextcloud
  title: Nextcloud
  description: >
    With over 400.000 deployments, Nextcloud is the most popular on-premises
    content collaboration platform you can download. 

    It scales from a Raspberry Pi with 2 users to globally distributed installations with tens of millions of users at major hosting providers.
  url: https://nextcloud.com/
  category: office
  icon: nextcloud.png
  author: Koen Swings
  version: e94f22caf95bc22a0b6c583fed2840a054b87b4f
  instanceName: nextcloud
networks:
  backend: null
services:
  nextcloud-app:
    image: nextcloud
    restart: no
    pull_policy: never
    volumes:
      - ./data/nextcloud:/var/www/html
    ports:
      - ${port}:80
    environment:
      - MYSQL_PASSWORD=${pass}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
    networks:
      - backend
  nextcloud-db:
    image: mariadb
    restart: no
    pull_policy: never
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${pass}
      - MYSQL_PASSWORD=${pass}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
  code:
    image: collabora/code
    restart: no
    pull_policy: never
    ports:
      - 9980:9980
    environment:
      - extra_params=--o:ssl.enable=false
    extra_hosts:
      #- nostalgic-lederberg.local:192.168.1.150
      - ${hostname}.local:${ip}
    networks:
      - backend
